version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuaSenha@123
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - appnet

  api:
    build: .
    container_name: sua-api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Credito;User Id=sa;Password=SuaSenha@123;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    networks:
      - appnet
    command: >
      sh -c "
        dotnet TesteTecnicoDotNet.Api
      "

volumes:
  sqlvolume:

networks:
  appnet:
